name: keep-render-awake

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes (UTC)
  workflow_dispatch:         # allows manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      PING_URL: ${{ secrets.PING_URL }}
    steps:
      - name: Ping backend
        run: |
          echo "Ping started at $(date -u)"
          if [ -z "$PING_URL" ]; then
            echo "ERROR: PING_URL secret is not set"
            exit 1
          fi
          # make a GET request and fail the job if non-2xx
          curl -fsS --retry 3 --retry-delay 5 "$PING_URL" -o /dev/null
          echo "Ping OK at $(date -u)"
